functionsDirectory = "/Users/calgon./Andrew-Allen-Site/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/calgon./Andrew-Allen-Site"
publishOrigin = "config"
functions = "/Users/calgon./Andrew-Allen-Site/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/reviews/google"
to = "/.netlify/functions/google-reviews"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/reviews/zillow"
to = "/.netlify/functions/zillow-reviews"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/stats"
to = "/.netlify/functions/stats"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/lead"
to = "/.netlify/functions/lead"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/media-assistant"
to = "/.netlify/functions/media-assistant"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]